### ISSUE TITLE
Pugx edit profile

### ISSUE THREAD

**Issue by darlington72** [PUGX/PUGXMultiUserBundle#117]
Hello everyone!

Thank you for this bundle which is very useful!

Thanks to this bundle, I designed two kind of account and it perfectly works to creating it.
But I don't succeed in editing profile.
Could you help me with an example code, like the documentation, to allow users edit their profiles?

Thanks a lot!

**Comment by garak** [comment]
Hi, thanks for asking.
Unfortunately, this is not a support forum. If you provide a working example with the expected behaviour and the actual behaviour, we can try to identify your problem. Otherwise, this issue will be closed.

**Comment by darlington72** [comment]
Hi Garak, 
I'm sorry for this mistake.. Thanks for your answe, here is my issue:

I wanted to add "edit profile" exactly like registration with pugx bundle like this:
(config.yml)
`pugx_multi_user:
  users:
    user_etudiant:
        entity:
          class: AP\UserBundle\Entity\Etudiant
        registration:
         ...
        profile:
          form:
            type: AP\UserBundle\Form\Type\ProfileEtudiantFormType
            name: fos_user_etudiant_edit_profile
            validation_groups:  [Profile, Default]

    user_representant:
        entity:
          class: AP\UserBundle\Entity\Representant
        registration:
          form:
           ...
       profile:
          form:
            type: AP\UserBundle\Form\Type\ProfileRepresentantFormType
            name: fos_user_representant_profile
            validation_groups:  [Profile, Default]`

So paths are directly connected to respective FormType.
This is okay, but when I try to modify different fields, they are not update...

Have you got any idea?

Thank you!

**Comment by garak** [comment]
What is the meaning of "they are not update"?

**Comment by darlington72** [comment]
For example, the field "address" of "user_representant" which is not updated in my database

**Comment by garak** [comment]
This is a partial information, you should go deep and debug it. Is your form valid? The queries you expect are not performed or performed wrongly? Etc.

**Comment by Muspi** [comment]
Hi, try to override FosUser ProfileController like this:

`namespace AppBundle\Controller;

use AppBundle\Entity\Candidate;
use AppBundle\Entity\Employer;
use AppBundle\Entity\Manager;
use FOS\UserBundle\Controller\ProfileController as BaseControler;
use Symfony\Component\HttpFoundation\Request;

class ProfileController extends BaseControler
{

    public function editAction(Request $request)
    {
        $user = $this->getUser();
        if ($user instanceof Employer){
            return $this->container
                ->get('pugx_multi_user.profile_manager')
                ->edit(Employer::class);
        }
        if ($user instanceof Candidate){
            return $this->container
                ->get('pugx_multi_user.profile_manager')
                ->edit(Candidate::class);
        }
        if ($user instanceof  Manager){
            return $this->container
                ->get('pugx_multi_user.profile_manager')
                ->edit(Manager::class);
        }

    }
}`

**Comment by Muspi** [comment]
Hello, try to override ProfileController of FOSUser like this, it worked for me:

```
use FOS\UserBundle\Controller\ProfileController as BaseControler;

class ProfileController extends BaseControler
{
    public function editAction(Request $request)
    {
            $user = $this->getUser();
            return $this->container
                ->get('pugx_multi_user.profile_manager')
                ->edit(get_class($user));
    }
}
```

As result, I have the good form and template defined in pugx_multi_user configuration.

**Comment by MaximStrutinskiy** [comment]
**I have another solution**
```
pugx_multi_user:
    users:
        manager:
            entity:
                class: MainBundle\Entity\Manager
            registration:
                form:
                    type: MainBundle\Form\FOSUser\FormManagerRegistrationType
                    name: app_user_manager_registration
                    validation_groups:  [Registration, Default]
            profile:
                form:
                    type: MainBundle\Form\FOSUser\FormProfileManagerEditInfoType
                    name: app_manager_profile_edit
                    validation_groups:  [Profile, Default]
        customer:
            entity:
                class: MainBundle\Entity\Customer
            registration:
                form:
                    type: MainBundle\Form\FOSUser\FormCustomerRegistrationType
                    name: app_user_customer_registration
                    validation_groups:  [Registration, Default]
            profile:
                form:
                    type: MainBundle\Form\FOSUser\FormProfileCustomerEditInfoType
                    name: app_customer_profile_edit
                    validation_groups:  [Profile, Default]
`
```
**Hear, you can add you'r custom/personal form to One of you user User types:**
````
pugx_multi_user:
    users:
        manager:
            profile:
                form:
                    type: MainBundle\Form\FOSUser\FormProfileManagerEditInfoType
                    name: app_manager_profile_edit
                    validation_groups:  [Profile, Default]
````**Example form**
```
<?php
namespace MainBundle\Form\FOSUser;

use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


/**
 * Class FormProfileManagerEditInfoType
 * @package MainBundle\Form\FOSUser
 */
class FormProfileManagerEditInfoType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'name',
                TextType::class,
                [
                    'required' => true,
                    'label' => 'Имя',
                ]
            )
            ->add(
                'soname',
                TextType::class,
                [
                    'required' => true,
                    'label' => 'Фамилия',
                ]
            )
            ->add(
                'patronymic',
                TextType::class,
                [
                    'required' => true,
                    'label' => 'Отчество',
                ]
            )
            ->add(
                'phone',
                IntegerType::class,
                [
                    'required' => true,
                    'label' => 'Телефон',
                ]
            )
            ->add(
                'address',
                TextType::class,
                [
                    'required' => false,
                    'label' => 'Адрес',
                ]
            );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => 'MainBundle\Entity\User',
            ]
        );
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'app_manager_profile_edit';
    }
}
```

Maybe someone will find this information useful.
