### ISSUE TITLE
registration template

### ISSUE THREAD

**Issue by ghost** [PUGX/PUGXMultiUserBundle#18]
After following the steps in the documentation whenever i go to the /register/client route i get this : 

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fos_user_registration_register" as such route does not exist.") in FOSUserBundle:Registration:register.html.twig at line 4.

The only way i could solve this was by uncommenting the registration route of FOSUB but i don't think it should be like this.

Here is my config for the client type user:

```
pugx_multi_user:
  users:
      client_user:
          entity:
              class: Acme\UserBundle\Entity\ClientUser
          registration:
              form:
                  type: Acme\UserBundle\Form\Type\ClientRegistrationFormType
                  name: fos_user_registration_form
                  validation_groups:  [Registration, Default]
              template: AcmeUserBundle:Registration:client.form.html.twig
          profile:
              form:
                  type: Acme\UserBundle\Form\Type\ClientProfileFormType
                  name: fos_user_profile_form
                  validation_groups:  [Profile, Default]
```
