### ISSUE TITLE
Only the first user type can be registered

### ISSUE THREAD

**Issue by approached** [PUGX/PUGXMultiUserBundle#29]
Only the first user type can be registered. When i change the config.yml the user, it will be changed to the other user.

```
pugx_multi_user:
  users:
    user_worker:
        entity:
          class: Mas\UserBundle\Entity\UserWorker
        registration:
          form:
            type: Mas\UserBundle\Form\Type\RegistrationUserWorkerFormType
          template: MasUserBundle:Registration:user_worker.form.html.twig
        profile:
          form:
            type: Mas\UserBundle\Form\Type\ProfileUserWorkerFormType
    user_customer:
        entity:
          class: Mas\UserBundle\Entity\UserCustomer
        registration:
          form:
            type: Mas\UserBundle\Form\Type\RegistrationUserCustomerFormType
          template: MasUserBundle:Registration:user_customer.form.html.twig
        profile:
          form:
            type: Mas\UserBundle\Form\Type\ProfileUserCustomerFormType
```

A other guy have the same problem:
http://stackoverflow.com/questions/17045253/symfony2-pugxmultiuserbundle-i-can-register-only-one-type-of-user
