### ISSUE TITLE
UserOne and UserTwo with same username authentication

### ISSUE THREAD

**Issue by SymfonyJr** [PUGX/PUGXMultiUserBundle#40]
Hi all!

There are two different types of users (UserOne and UserTwo). And both of them have users with the same username "testuser".

in parameters.yml

``` yaml
parameters:
    pugx_user_discriminator_parameters:
        classes:
            user_one:
                entity: Acme\DemoBundle\Entity\UserOne
                ...
            user_two:
                entity: Acme\DemoBundle\Entity\UserTwo
                ...
```

PUGXMultiUserBundle/UserDiscriminator sets an array with these two entities:

```
["Acme\DemoBundle\Entity\UserOne", "Acme\DemoBundle\Entity\UserTwo"]
```

Both types have different login pages with different routes:

``` yaml
user_one_login:
    pattern:  /user_one/login
    defaults: { _controller: AcmeDemoBundle:UserOneSecurity:login }

user_one_check:
    pattern:  /user_one/login_check
    defaults: { _controller: AcmeDemoBundle:UserOneSecurity:check }

user_two_login:
    pattern:  /user_two/login
    defaults: { _controller: AcmeDemoBundle:UserTwoSecurity:login }

user_two_check:
    pattern:  /user_two/login_check
    defaults: { _controller: AcmeDemoBundle:UserTwoSecurity:check }
```

Controllers are extended from _FOS\UserBundle\Controller\SecurityController_ and don't have _checkAction_ method defined - parent method used.

**Issue:**
When UserTwo with username "testuser" logins, PUGXMultiUserBundle/UserManager returns UserOne with the same username, because it has been found in the first entity from UserDiscriminators::$entities.

**Question:**
How this issue could be solved?

Thank you
