### ISSUE TITLE
Auth Listener & Other providers

### ISSUE THREAD

**Issue by ogizanagi** [PUGX/PUGXMultiUserBundle#63]
Hi,

Thank you for your great work.

I think there is a problem with the `AutenticationListener` and the `setClass` method of the `UserDiscriminator`.
Indeed, in case of a configured chained provider, with a mix of `in_memory users`, `PUGXUsers` and other `custom providers`, login fails because of this listener, or even for the use of another simple provider. Example for in_memory user:

```
Impossible to set the class discriminator, because the class "Symfony\Component\Security\Core\User\User" is not present in the entities list
```

with the following security conf : 

``` yaml
providers:
        fos_users:
            id: fos_user.user_provider.username_email
        admin:
            memory:
                users:
                    - { name: %main_admin_login%, password: %main_admin_password%, roles: ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN'] }
        application:
            id: acme.application.provider
        chained_provider:
            chain:
                providers:
                    - admin
                    - fos_users
                    - application
```

The incriminated method is : 

``` php
protected function discriminate($user)
{
    $this->userDiscriminator->setClass(get_class($user), true);
}
```

This method is called on every login & switch user events, and generates an exception if the user type isn't one of the configured PUGX users, with a discriminator. Basically, this means it will fail on every login attempt with another user type, with a chained or any other provider, which I consider isn't a good way to achieve what this bundle is meant for : allow users inheritance. This should not alter the basic symfony's functionnalities.

Maybe the LogicException thrown by the `UserDiscriminator::setClass` method should be catch in this listener ?
Is this LogicException really usefull ? For which cases ?
Is this AutenticationListener even necessary ? Isn't the discriminator set by the UserManager ?

**Comment by Farshadi73** [comment]
I have same problem with fos user bundle chain_provider (static users)... 
I do your advice, but still have problem in check_login route :( 
```

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]

        in_memory:
            memory:
                users:
                    user:  { name: user, password: user, roles: [ 'ROLE_USER' ] }
                    admin: { name: admin, password: admin, roles: [ 'ROLE_ADMIN' ] }

        fos_userbundle:
            id: fos_user.user_provider.username

```
